version: '3'

services:
  application:
    image: "localhost:6000/tokens:latest"
    ports:
      - "40000:8080"
    environment:
      PORT: 8080
      DEBUG: app, app:*
      PRIVATE_KEY: './private-key.pem'
      ISS: tokener
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 60s
      timeout: 10s
      retries: 3