# @name createToken
POST http://localhost:40000/tokens?expiresIn=1h
Content-Type: application/json
Authorization: Bearer {{createToken.response.body.$.token}}

{
  "sub": "salmiin",
  "aud": "terminal-sherminal",
  "iss": "PacinTokenPalvelu"
}

###
GET http://localhost:8080/status
Content-Type: application/json